default: &default
 adapter: postgresql
 encoding: unicode
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 username: postgres
 password: postgres
 host: localhost

development:
 <<: *default
 database: social_media_development

test:
 <<: *default
 database: social_media_test

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:supabase, :database, :database_name) %>
  username: <%= Rails.application.credentials.dig(:supabase, :database, :user) %>
  password: <%= Rails.application.credentials.dig(:supabase, :database, :password) %>
  host: <%= Rails.application.credentials.dig(:supabase, :database, :host) %>
  port: <%= Rails.application.credentials.dig(:supabase, :database, :port) %>
  sslmode: require
