unverified_account_delete_job:
  cron: "*/15 * * * *" # At every 15 minutes
  class: "UnverifiedAccountDeleteJob"

otp_delete_jon:
  cron: "*/15 * * * *" # At every 15 minutes
  class: "OtpDeleteJob"
