test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

supabase_dev:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:supabase, :storage, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:supabase, :storage, :secret_access_key) %>
  region: <%= Rails.application.credentials.dig(:supabase, :storage, :region) %>
  bucket: Development
  endpoint: <%= Rails.application.credentials.dig(:supabase, :storage, :endpoint) %>
  force_path_style: true

supabase_prod:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:supabase, :storage, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:supabase, :storage, :secret_access_key) %>
  region: <%= Rails.application.credentials.dig(:supabase, :storage, :region) %>
  bucket: <%= Rails.application.credentials.dig(:supabase, :storage, :bucket) %>
  endpoint: <%= Rails.application.credentials.dig(:supabase, :storage, :endpoint) %>
  force_path_style: true
